### ISSUE TITLE
Can't download anything

### ISSUE THREAD

**Issue by hellbreaker619** [DaxEleven/Rule34.xxx-Downloader#1]
When I click on download it just finishes really quickly  and when I check the folder I designated for downloads there is nothing there

**Comment by Dax-Eleven** [comment]
Bugs fixed in version 1.0.3

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by DaxEleven** [comment]
Fixed in v.1.0.3
