### ISSUE TITLE
it won't download video's

### ISSUE THREAD

**Issue by iforgotmyskin** [DaxEleven/Rule34.xxx-Downloader#10]
it worked like a week ago but when i tried to download today it won't download videos

**Comment by DaxEleven** [comment]
Are you sure you're using the latest version of the program (1.0.3)?
Works for me
![demo](https://github.com/DaxEleven/Rule34.xxx-Downloader/assets/37029321/c9999ffe-a0d2-4d15-bfe1-42a1d3422965)
