### ISSUE TITLE
The app requires .NET Framework 4.8.1

### ISSUE THREAD

**Issue by GilaR11** [DaxEleven/Rule34.xxx-Downloader#12]
No matter what I do, I still get the error that it is not installed.
![dsadasdada](https://github.com/DaxEleven/Rule34.xxx-Downloader/assets/149058109/f774fb3e-f832-4538-b8f1-ae683323c923)
In the control panel I enabled and disabled, reinstalled, restored, installed previous versions (all except 3.5 and 2.0)
Nothing helps

**Comment by DaxEleven** [comment]
Just install .NET Framework 4.8.1 from this link
https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481
Runtime version
![image](https://github.com/DaxEleven/Rule34.xxx-Downloader/assets/37029321/1575cb34-7ae7-4c25-a502-0610d0607891)
