### ISSUE TITLE
Your are offline, please check your internet connection (failed to connect to rule34.xxx

### ISSUE THREAD

**Issue by 4Sol** [DaxEleven/Rule34.xxx-Downloader#14]
Your are offline, please check your internet connection (failed to connect to rule34.xxx

what's wrong?

**Comment by vvvoodie** [comment]
Hi there! Experienced the same issue, which was resolved after installing [.NET Framework 4.8.1](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net481).

**Comment by krocksname** [comment]
i installed net framework 4.8.1, and i try to open R34.Downloader.exe but,  nothing changes. 

Still, You are offline, please check your internet connection

 what should i do? please somebody help me :(

**Comment by Jagailo** [comment]
Hello @4Sol,
When launching the app, I added a check to see if there is a connection to the URL "https://rule34.xxx", if not, show an error.
Basically, if you see this error, it means your computer cannot receive a response from this site.

The problem may be client or server.
Server: the site isn't really responding, perhaps it isn't working. As a rule, such large sites don't remain offline for a long time.
Client: either you don't have Internet connection at all (which is unlikely), or something is blocking the connection. Perhaps this is some kind of parent control locally on the PC (software, antivirus) or in some countries where pornography is prohibited, this is done by Internet provider.

Can you access Rule34 website in a browser without any VPN?

**Comment by DaxEleven** [comment]
Hello
When launching the app, I added a check to see if there is a connection to URL "https://rule34.xxx/", if not, show an error.
Basically, if you see this error, it means your computer cannot receive a response from this site.

The problem may be client or server.
Server: the site isn't really responding, perhaps it isn't working. As a rule, such large sites don't remain offline for a long time.
Client: either you don't have Internet connection at all (which is unlikely), or something is blocking the connection. Perhaps this is some kind of parent control locally on the PC (software, antivirus) or in some countries where pornography is prohibited, this is done by Internet provider.

@4Sol, @krocksname, can you access Rule34 website in a browser without any VPN?

**Comment by aussax** [comment]
Tried VPN, issue has not been resolved

**Comment by 4Sol** [comment]
> Hello When launching the app, I added a check to see if there is a connection to URL "https://rule34.xxx/", if not, show an error. Basically, if you see this error, it means your computer cannot receive a response from this site.
> 
> The problem may be client or server. Server: the site isn't really responding, perhaps it isn't working. As a rule, such large sites don't remain offline for a long time. Client: either you don't have Internet connection at all (which is unlikely), or something is blocking the connection. Perhaps this is some kind of parent control locally on the PC (software, antivirus) or in some countries where pornography is prohibited, this is done by Internet provider.
> 
> @4Sol, @krocksname, can you access Rule34 website in a browser without any VPN?

Yes, can access web site with no issues
I don't use anything that prevent the connections as well

**Comment by DaxEleven** [comment]
To be honest, I don't think the problem is in the app. Something doesn't allow access to the network.

**Comment by 4Sol** [comment]
How to find out what is that?

**Comment by xKuruh** [comment]
It worked last month great now im also having this issue

**Comment by DaxEleven** [comment]
Not directly related to this application.
