### ISSUE TITLE
The remote server returned an error:(429) too many requests

### ISSUE THREAD

**Issue by Instaplays** [DaxEleven/Rule34.xxx-Downloader#17]
started happening this month. i can download a certain amount or few hours

**Comment by Nuriell** [comment]
Adding a max number of simultaneous downloads will solve this, an option to make it download a single file will be the most long-time follproof fix.

**Comment by Nuriell** [comment]
Now it has become a major issue, every 100 images it gives an error and you have to wait 10+ seconds bofeore even being able to click download and restart the procedure, if you want to download 200 images you have to wait about a minute.

Before starting fresh on a new day gave you 800+ images to download in the first run, now is 200-400, it's insufferable for an automatic downloader.

**Comment by DaxEleven** [comment]
This app has always worked synchronously, downloading only 1 file at a time.
Perhaps on the R34 side, load protection was introduced.
Perhaps it is worth making an artificial pause between files.

**Comment by DaxEleven** [comment]
I didn't notice this in version 1.0.4.
