### ISSUE TITLE
Add support for Aria2

### ISSUE THREAD

**Issue by wszdexdrf** [DaxEleven/Rule34.xxx-Downloader#18]
Adding support for Aria2 would be a big improvement, due to the performance improvements implemented in Aria2 for faster downloads of multiple files. Given the current working of the library, this wouldn't require large changes.

**Relevent Resources:**
- https://aria2.github.io/manual/en/html/index.html
- https://aria2.github.io/manual/en/html/libaria2.html

**Comment by DaxEleven** [comment]
I don't see the point in this
