### ISSUE TITLE
How can i turn off the limit

### ISSUE THREAD

**Issue by IcYHurTz** [DaxEleven/Rule34.xxx-Downloader#2]
i have been try to change it for days looking everywhere in the code

**Comment by Dax-Eleven** [comment]
Bugs fixed in version 1.0.3
The limit has been raised to 65535

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by DaxEleven** [comment]
The limit cannot be turned off, now it is 65535.
