### ISSUE TITLE
rule34py

### ISSUE THREAD

**Issue by nasayuzaki050** [DaxEleven/Rule34.xxx-Downloader#22]
hola, hace tiempo cree mi propio código con la librería de rule34py, pero recién lo reabrí, y me di cuenta de que me da error desde el módulo de rule34py, ahora ya no importa los módulos, como te conectas con el api de r34? 
![Captura de pantalla (242)](https://github.com/user-attachments/assets/b13193a4-58f3-4790-8b10-b2c942c2f60f)
Captura del error en colab (donde lo hice primero) y captura de python ( pq se me hace ineficiente que los descargue en el espacio virtual y no en el pc)
![Captura de pantalla (243)](https://github.com/user-attachments/assets/5966b125-78aa-4874-8b61-ab7e570a98b2)

**Comment by DaxEleven** [comment]
Hello, perhaps you have confused the repositories, this is a C# app and doesn't use any Python libraries.

**Comment by nasayuzaki050** [comment]
> Hello, perhaps you have confused the repositories, this is a C# app and doesn't use any Python libraries.

Lo se, ya encontré el error con la api (librería para python), la versión 2.0.0 estaba fallando, no descargaba los módulos necesarios, por eso pregunté por el modo html, pero solo basto con hacer pip a la versión 1.4.2? Creo, de todos modos funciona, gracias por responder ksksls
