### ISSUE TITLE
Download link is private

### ISSUE THREAD

**Issue by SanduAnghel** [DaxEleven/Rule34.xxx-Downloader#3]
i try to download the installer but is private access can u make it public again pls

**Comment by masterdjboner** [comment]
bump. still private

**Comment by Sicanpanda35** [comment]
bump

**Comment by hqnt** [comment]
bump

**Comment by YakuzaSuske** [comment]
https://drive.google.com/file/d/1ZtA-YbniCJ5WKlMqxAAE1Wc3KdwaWXnG/view?usp=sharing

**Comment by Dax-Eleven** [comment]
Bugs fixed in version 1.0.3
Public download link

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by DaxEleven** [comment]
Link updated
