### ISSUE TITLE
can someone give me the installer ?

### ISSUE THREAD

**Issue by SanduAnghel** [DaxEleven/Rule34.xxx-Downloader#8]
the download link is private if someone have the installer i will be glad

**Comment by hawkridge123** [comment]
Would also love the installer...did you get hold of it ?

**Comment by YakuzaSuske** [comment]
> the download link is private if someone have the installer i will be glad

https://drive.google.com/file/d/1ZtA-YbniCJ5WKlMqxAAE1Wc3KdwaWXnG/view?usp=sharing

**Comment by Dax-Eleven** [comment]
Bugs fixed in version 1.0.3
Public download link

The new version can be downloaded from my 2nd repository:
https://github.com/Dax-Eleven/Rule34.xxx-Downloader

**Comment by DaxEleven** [comment]
Link updated
